# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_lord', models.BooleanField(default=False, verbose_name='Is lord?')),
                ('image', models.ImageField(upload_to='characters/images/', verbose_name='Logo')),
                ('likes', models.PositiveIntegerField(blank=True, default=0, verbose_name='Likes')),
                ('dislikes', models.PositiveIntegerField(blank=True, default=0, verbose_name='Likes')),
                ('dislikes_quantity_to_die', models.PositiveIntegerField(help_text='Min quantity of dislikes quantity to die', verbose_name='Dislikes to die')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('logo', models.ImageField(upload_to='families/logos/', verbose_name='Logo')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='characters.House'),
        ),
    ]
